In [ ]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 

pd.set_option("display.max_columns", None) 
df = pd.read_csv("E:\SmartStock-AI\Data\Raw\demand_forecasting_inventory_data.csv")

df.head(10)

,Date,Product_ID,Product,Category,Store,City,Price,Discount,Promotion,Inventory,Sales
0,2023-01-01,P001,Laptop,Electronics,S01,Pune,51664,0,0,125,6
1,2023-01-02,P001,Laptop,Electronics,S01,Pune,55837,0,0,121,4
2,2023-01-03,P001,Laptop,Electronics,S01,Pune,53257,0,0,118,3
3,2023-01-04,P001,Laptop,Electronics,S01,Pune,53285,0,0,115,3
4,2023-01-05,P001,Laptop,Electronics,S01,Pune,40087,15,1,108,7
5,2023-01-06,P001,Laptop,Electronics,S01,Pune,57449,0,0,105,3
6,2023-01-07,P001,Laptop,Electronics,S01,Pune,51029,5,0,100,5
7,2023-01-08,P001,Laptop,Electronics,S01,Pune,50244,5,0,96,4
8,2023-01-09,P001,Laptop,Electronics,S01,Pune,45144,15,1,89,7
9,2023-01-10,P001,Laptop,Electronics,S01,Pune,59544,5,0,85,4

In [2]:
df.shape

(159858, 11)

In [3]:
df.columns

Index(['Date', 'Product_ID', 'Product', 'Category', 'Store', 'City', 'Price',
       'Discount', 'Promotion', 'Inventory', 'Sales'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159858 entries, 0 to 159857
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Date        159858 non-null  object
 1   Product_ID  159858 non-null  object
 2   Product     159858 non-null  object
 3   Category    159858 non-null  object
 4   Store       159858 non-null  object
 5   City        159858 non-null  object
 6   Price       159858 non-null  int64
 7   Discount    159858 non-null  int64
 8   Promotion   159858 non-null  int64
 9   Inventory   159858 non-null  int64
 10  Sales       159858 non-null  int64
dtypes: int64(5), object(6)
memory usage: 13.4+ MB

In [5]:
df.describe(include="all")

,Date,Product_ID,Product,Category,Store,City,Price,Discount,Promotion,Inventory,Sales
count,159858,159858,159858,159858,159858,159858,159858.000000,159858.000000,159858.000000,159858.000000,159858.000000
unique,731,23,23,5,10,8,NaN,NaN,NaN,NaN,NaN
top,2023-08-29,P001,Laptop,Electronics,S03,Mumbai,NaN,NaN,NaN,NaN,NaN
freq,220,7310,7310,36550,16813,32004,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,6367.849529,4.343661,0.099657,392.402883,44.676607
std,NaN,NaN,NaN,NaN,NaN,NaN,12481.809208,5.523459,0.299543,727.943867,41.354914
min,NaN,NaN,NaN,NaN,NaN,NaN,31.000000,0.000000,0.000000,20.000000,1.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,292.000000,0.000000,0.000000,77.000000,12.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,857.000000,5.000000,0.000000,118.000000,34.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,4055.000000,5.000000,0.000000,223.000000,64.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,64902.000000,25.000000,1.000000,4886.000000,545.000000

In [6]:
df.isnull().sum()

Date          0
Product_ID    0
Product       0
Category      0
Store         0
City          0
Price         0
Discount      0
Promotion     0
Inventory     0
Sales         0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
for col in df.columns:
    print(f"\n{col}")
    print(df[col].nunique())

Date
731

Product_ID
23

Product
23

Category
5

Store
10

City
8

Price
21945

Discount
7

Promotion
2

Inventory
4359

Sales
388